id: AEED11626
title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The Nucleus
  of Blessings’
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:33:08.898587
  last_modified_at: 2022-02-28 23:33:08.898592
