id: AEED11626
title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives of the
  Supreme Holders of the Non-Sectarian Teachings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:33:08.887120
  last_modified_at: 2022-02-28 23:33:08.887123
