id: AEED11626
title: A Short Supplication to Tārā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:33:08.848570
  last_modified_at: 2022-02-28 23:33:08.848580
