id: AEED11626
title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:33:08.858876
  last_modified_at: 2022-02-28 23:33:08.858886
