id: AEED11626
title: Vajrakīla Tsok Prayer from Sangtik Korsum
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:33:08.907899
  last_modified_at: 2022-02-28 23:33:08.907903
