id: AEED11626
title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities Based
  on a Single Substance to Easily Conclude Approach and Accomplishment'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:33:08.863290
  last_modified_at: 2022-02-28 23:33:08.863298
