id: AEED11626
title: Prayer to Kongtrul Yönten Gyatso
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:33:08.873108
  last_modified_at: 2022-02-28 23:33:08.873112
