id: AEED11626
title: Prayer for Peace and Stability in Tibet
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:33:08.867434
  last_modified_at: 2022-02-28 23:33:08.867456
