id: AEED11626
title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the Female
  Practice of the Queen of Great Bliss, from the Heart Essence of the Vast Expanse'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:33:08.875234
  last_modified_at: 2022-02-28 23:33:08.875238
