id: AEED11626
title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the Liberational
  Life of the Omniscient Jamyang Khyentse Wangpo'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:33:08.891465
  last_modified_at: 2022-02-28 23:33:08.891469
