id: AEED11626
title: 'The Fount of Longevity: The Chimé Pakmé Nyingtik Lineage Prayer'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:33:08.884324
  last_modified_at: 2022-02-28 23:33:08.884355
