id: AEED11626
title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:33:08.871626
  last_modified_at: 2022-02-28 23:33:08.871629
